### ISSUE TITLE
Wrong regex?

### ISSUE THREAD

**Issue by frederikhors** [svelte-add/tailwindcss#57]
I'm trying to use this code:

```js
defaultExtractor: (content) => [
  // If this stops working, please open an issue at https://github.com/svelte-add/tailwindcss/issues rather than bothering Tailwind Labs about it
  ...tailwindExtractor(content),
  // Match Svelte class: directives (https://github.com/tailwindlabs/tailwindcss/discussions/1731)
  ...[...content.matchAll(/(?:class:)*([\\w\\d-/:%.]+)/gm)].map(([_match, group, ..._rest]) => group),
],
```

but this regex:

```regex
(?:class:)*([\\w\\d-/:%.]+)
```

is detected as wrong, why?

Is wrong here too: https://regex101.com/r/sLLGqG/2

**Comment by babichjacob** [comment]
If you copied this from the source code https://github.com/svelte-add/tailwindcss/blob/7fca5f5840d95dbc3a524e2d97c7fc8961dfbb1c/__run.js#L21-L24

then it won't work because it's doubly escaped (the `\\`s).

If you run the adder (as I just tested), it will be written to your Tailwind config file correctly. Is that what you did and this is still a problem?

**Comment by frederikhors** [comment]
I'm using PurgeCSS manually, not with SvelteKit. I'm copying the code from the source.

Where is the `\\s`?

Do you mean `\\w\\d`?

**Comment by babichjacob** [comment]
> Do you mean `\\w\\d`?


Yes

**Comment by frederikhors** [comment]
Ok. If I use this is works:

```regex
(?:class:)*([\w\d-/:%.]+)
```
