### ISSUE TITLE
[Vite] TailwindCSS 2.2 JIT no longer tracks updated Svelte files

### ISSUE THREAD

**Issue by GrygrFlzr** [svelte-add/tailwindcss#59]
Since 2.2 (tailwindlabs/tailwindcss#4514) the JIT engine switches to using the "tracking" context by default instead of "watching" context, which requires support in Vite. There's an issue about this filed at tailwindlabs/tailwindcss#4683 but I figure it's good to track this here as well.

Current workarounds:
- Use `TAILWIND_MODE=watch` env var, which is ugly and not cross-platform without `cross-env`, and apparently doesn't trigger HMR
- Start a separate tailwind process with `npm-run-all`
- Downgrade tailwind to 2.1

Proper Fix:
https://github.com/vitejs/vite/commit/6eaec3ab74d126310d93f8a93f8577bed1c3f474 should in theory fix this, although I can confirm that the CI failing tests on Windows is not a fluke, I can replicate it on my machine.

**Comment by maxmellen** [comment]
Can confirm I'm running into this issue as well.
The `TAILWIND_MODE=watch` trick is a lifesaver though 👍

**Comment by techniq** [comment]
@GrygrFlzr Windows fix might have just been checked in - https://github.com/vitejs/vite/commit/41b193c8500b28efc3e61a0387498ded3840c6a1

**Comment by babichjacob** [comment]
Putting
```js

const mode = process.env.NODE_ENV;
const dev = mode === "development";
process.env.TAILWIND_MODE = dev ? "watch" : "build";
```

in `svelte.config.js` (or `svelte.config.cjs` for people using non-SvelteKit Vite) fixes it.

**Comment by babichjacob** [comment]
Also note that due to #58, this project currently isn't able to produce a JIT Tailwind setup because `svelte-add` doesn't have an argument parser to detect that `--jit` is even being passed (and implementing this is harder than it sounds which is why it hasn't happened yet). An empty JIT config can be found here: https://github.com/svelte-add/tailwindcss/blob/76a390563f3b9d34938178b44c2b1a3c4f2d3eeb/__run.js#L38-L50

**Comment by babichjacob** [comment]
Alternatively, https://github.com/sveltejs/kit/pull/1715
